### ISSUE TITLE
APIError: API query failed: [Errno 101] Network is unreachable.

### ISSUE THREAD

**Issue by josve05a** [earwig/copyvios#23]
https://www.uploady.com/#!/download/rRSTCPgwFN~/JcR~luRiN7H7YpUq on https://tools.wmflabs.org/copyvios/?lang=en&project=wikipedia&title=User%3ASijupm%2Fsandbox

**Comment by josve05a** [comment]
Also 'Errno' is that a typo of Error?

**Comment by josve05a** [comment]
Hmm...works for me now...

**Comment by earwig** [comment]
Nothing to say about this kind of error. It's going to happen sometimes whenever there are intermittent network issues with Labs. There's little we can do about it.
