### ISSUE TITLE
wikiversity support

### ISSUE THREAD

**Issue by josve05a** [earwig/copyvios#30]
I can't run the copyvios-tool on https://tools.wmflabs.org/copyvios/?lang=en&project=wikiversity&title=Decolonising+Science%2FReading+List&oldid=&use_engine=0&use_links=0&turnitin=0&action=compare&url=https%3A%2F%2Fmedium.com%2F%40chanda%2Fdecolonising-science-reading-list-339fb773d51f

It says "The given page doesn't seem to exist: Decolonising Science/Reading List." and links to beta.wikiversity.org, even though I've selected en.wikiversity

**Comment by earwig** [comment]
It's interesting. Looks like beta.wikiversity [reports its own language](https://beta.wikiversity.org/w/api.php?action=query&meta=siteinfo) as "en", so I think I understand how this happened. Anyway, I manually corrected the language entry in the database and it seems to work now. Shouldn't happen again.
