### ISSUE TITLE
APIError: API query failed: JSON could not be decoded.

### ISSUE THREAD

**Issue by AntiCompositeNumber** [earwig/copyvios#39]
Got an API error when loading https://tools.wmflabs.org/copyvios/?lang=en&project=wikipedia&title=User:Lernglobaluk/sandbox&url=. The link was generated by {{AFC submission}}.
> Traceback (most recent call last):
>  File "/data/project/copyvios/www/python/src/app.py", line 38, in inner
>    return func(*args, **kwargs)
>  File "/data/project/copyvios/www/python/src/app.py", line 103, in index
>    query = do_check()
>  File "./copyvios/checker.py", line 41, in do_check
>    _get_results(query, follow=not _coerce_bool(query.noredirect))
>  File "./copyvios/checker.py", line 52, in _get_results
>    page.get()  # Make sure that the page exists before we check it!
>  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/page.py", line 587, in get
>    rvprop="content|timestamp", rvslots="main")
>  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/site.py", line 716, in api_query
>    return self._api_query(kwargs)
>  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/site.py", line 254, in _api_query
>    return self._handle_api_result(response, params, tries, wait, ae_retry)
>  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/site.py", line 295, in _handle_api_result
>    raise exceptions.APIError(e)
> APIError: API query failed: JSON could not be decoded.

Using https://tools.wmflabs.org/copyvios/ worked normally.

**Comment by earwig** [comment]
I'm still investigating this, but it seems like either a strange bug in the MediaWiki API itself or that I'm misusing it in some subtle way. https://phabricator.wikimedia.org/T230526

**Comment by earwig** [comment]
It's fixed now.
