### ISSUE TITLE
Removing some sites from the "checked sources"

### ISSUE THREAD

**Issue by psubhashish** [earwig/copyvios#43]
Hi, I am from the Odia-language Wikipedia and I was checking your amazing tool after a colleague [mentioned](https://or.wikipedia.org/wiki/Topic:Vhtdls7o5lcbkz8u) about it. It's a tool many of us in the Wikipedia community might not know and it can come very handy. And I think, to make it more efficient, it would probably be a good idea to blacklist some of the sites that duplicate Wikipedia content as they are working against the whole purpose. An example here is "Wikipedia Top 100" list on Hatnote (e.g. see English list [here](https://top.hatnote.com/en/)) which lists the top 100 articles on a Wikipedia. It's ironic if an article is read more and makes it to this list and that duplication of content is flagged in the Copyvio Detector, isn't it. But it is not an issue of blacklisting just one site. I think a good idea would be to maintain, if that is possible given your time and other commitments, a list of all such sites that the tool should not search in. Thanks much again for bringing out this tool.

**Comment by earwig** [comment]
Thank you for your kind words.

There is already such a list. If you reread the tool description, it says:

> Be aware that other websites can copy from Wikipedia, so check the results carefully, especially for older or well-developed articles. Specific websites can be skipped by being added to the excluded URL list.

This links to https://en.wikipedia.org/wiki/User:EarwigBot/Copyvios/Exclusions, where you can add these exclusions.
